service: employee-service

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

functions:
  createEmployee:
    handler: src/handlers/employeeHandlers.createEmployee
    events:
      - http:
          path: employee
          method: post
  getEmployeeById:
    handler: src/handlers/employeeHandlers.getEmployeeById
    events:
      - http:
          path: employee/{id}
          method: get
  updateEmployee:
    handler: src/handlers/employeeHandlers.updateEmployee
    events:
      - http:
          path: employee/{id}
          method: put
  deleteEmployee:
    handler: src/handlers/employeeHandlers.deleteEmployee
    events:
      - http:
          path: employee/{id}
          method: delete

resources:
  Resources:
    EmployeesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
